language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RNz013wumqJGx49+ySpnlIv44c4xjfQ3K1g4HvnL4v+yg8fLViX08jcOANNhrQw3a7GMh3464Zi74gB8Iu8+C2kdsG0vZ/n12iWJV6SIyYjfTMo+Vkl6NUQnZuCIJHI+76fLMCUTgWJBsufyNV/f9jMxyYNSsqbL9x1Ld2H72Xg=
  file:
    - 'datalist-interface.js'
    - 'datalist-interface.min.js'
  on:
    tags: true
